export const ADD_CONTENT = "ADD_CONTENT";
export const GET_CONTENT = "GET_CONTENT";
export const UPDATE_CONTENT = "UPDATE_CONTENT";
export const DELETE_CONTENT = "DELETE_CONTENT";
export const BLOG_HISTORY_CONTENT = "BLOG_HISTORY_CONTENT";
export const LOAD_BLOG_HISTORY_CONTENT = "LOAD_BLOG_HISTORY_CONTENT";

export const TOGGLE_KEYWORD = "TOGGLE_KEYWORD";
export const REMOVE_KEYWORD = "REMOVE_KEYWORD";
export const DATE_OF_FAST = "DATE_OF_FAST";
export const DATE_OF_LAST = "DATE_OF_LAST";
